spring:
  application:
    name: mprProjectMvn
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: student
    password: student
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true